# Generated by Django 2.1 on 2018-10-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
    ]
