# Generated by Django 2.1 on 2018-10-30 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20181030_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='board',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
